### config data module ###
data_module:
  _target_: data_module.MNIST_DataModule

### config network model ###
model:
  _target_: models.MNISTModel

### config Trainer ###
trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 10
  devices: "auto"

  callbacks:
    - _target_: callbacks.PlotImageClassification

  logger:
    - _target_: pytorch_lightning.loggers.TensorBoardLogger
      save_dir: "logs"
      name: "demo_mnist"
